#ifndef HOME_H
#define HOME_H

#include <QDialog>

namespace Ui{
    class HomePage;
}



class HomePage : public QDialog{
    Q_OBJECT



public:
    explicit HomePage(QWidget *parent = nullptr);

    ~HomePage();


private slots:

    void on_navigateToLoginButton_clicked(); //slot for handling the login button being clicked

    void on_navigateToRegisterButton_clicked(); //slot for handling the registration button being clicked


private:

    Ui::HomePage *ui; //pointer to autogenerated ui class from home.ui

};
#endif //HOME_H
