#ifndef LANDINGPAGE_H
#define LANDINGPAGE_H

#include <QDialog>

namespace Ui{
    class LandingPage;
}

class HomePage; // Forward declaration

class LandingPage : public QDialog{
    Q_OBJECT

public:
    explicit LandingPage(QWidget *parent = nullptr);

    ~LandingPage();

private slots:

    void on_navigateToLoginButton_clicked(); //slot for handling the login button being clicked

    void on_navigateToRegisterButton_clicked(); //slot for handling the registration button being clicked

private:

    Ui::LandingPage *ui; //pointer to autogenerated ui class from home.ui

};
#endif //LANDINGPAGE_H
