#include "home.h"
#include "ui_home.h" // this is generated by uic from home.ui


#include "../LoginPage/loginpage.h"

#include <QDebug>

//Constructor This  initializes homepage and sets up the ui from home.ui

HomePage::HomePage(QWidget *parent) :
    QDialog(parent), 
    ui(new Ui::HomePage)
{
    ui->setupUi(this); //setup the widgets and layouts designed in home.ui
}

//Destructor: Deletes the UI object to free resources
HomePage::~HomePage(){

    delete ui; 
}

//Slot for handling the login buttons clicked 
void HomePage::on_navigateToLoginButton_clicked(){

    qDebug() << "navigateToLoginButton_clicked on HomePage";

    LoginPage loginDialog(nullptr);
    loginDialog.setAttribute(Qt::WA_DeleteOnClose);

    this->accept(); // Close HomePage and signal acceptance

    loginDialog.exec(); // Show LoginPage modally
    // Flow returns to main.cpp after LoginPage is closed
}

void HomePage::on_navigateToRegisterButton_clicked()
{
    qDebug() << "navigateToRegisterButton_clicked on HomePage";
    //Implement navigation to RegistrationPage
    this->accept(); // For now, behave like login button for flow
}